### ISSUE TITLE
Compensate Drive latency

### ISSUE THREAD

**Issue by DaniEll-AT** [bruxy70/Venetian-Blinds-Control#7]
I am currently using the test-branch of this great custom component.

My hardware is:

- Sonoff 4CH
- Somfy J4 WT

The tilt-time of my blinds is ~1200ms (measured by me). The problem i got is, small changes in tilt do not work.
According to the [Somfy J4 WT Data Sheet](https://www.somfy.info/download_sheet/5134391/5134391A_J4_WT_Protect-EN.pdf):

> Continuous orders of at least 200 ms must be sent to the drive to ensure proper execution.

My guess is, a setting like "actuator-activation-time" would help in such cases.
So i could configure:
```
actuator-activation-time: 200ms
tilt_duration: 1000ms
```

The time to change the tilt should then be calculated like this:
`actuator-activation-time + (tilt_duration * tilt-difference)`

What do you think? Have you seen such cases before?

**Comment by pawelma** [comment]
Hey. Yes, I saw that one for my drive, but I wasn't able to find anything useful in Sonesse motor specs. Although, when doing measurements it looked like it was not very deterministic, but it might be that tests I run were not accurate enough to show how it's behaving (methodology was doing repeated OPENs/Closes by Xms multiple times writing the distance travelled and then repeating for increased number of seconds).

Looking at the proposal solution, it looks like it should work, but this is not just a tilt. Position also would be affected if for example, tilt is already 'CLOSED' and movement of blinds is set to `CLOSING`. In the mentioned case the formula should still work, but it's no longer, a `tilt` but `actuator activation`. I think that it deserves the own 'method'.

**Comment by pawelma** [comment]
It depends on the usecase and motor someone have :) And I think overachievement is bad from UI perspective, but it is better than your example when no change has been done. Would incrementing by 1% (which is ~100ms in your setup) 100 times cause no movement at all, or maybe the difference happens when fully Open/Closed or after a while or after change of the direction (if latter is it immediate change of direction or after let's say 1 second)?
